# Generated by Django 4.1.7 on 2026-02-04 10:57

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('_id', models.CharField(db_column='_id', max_length=100, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('duration_minutes', models.IntegerField()),
                ('calories_burned', models.IntegerField()),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('_id', models.CharField(db_column='_id', max_length=100, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=200)),
                ('team_id', models.CharField(max_length=100)),
                ('total_activities', models.IntegerField(default=0)),
                ('total_calories', models.IntegerField(default=0)),
                ('total_duration_minutes', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leaderboard',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('_id', models.CharField(db_column='_id', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', djongo.models.fields.JSONField(default=list)),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.CharField(db_column='_id', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('team_id', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', djongo.models.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('_id', models.CharField(db_column='_id', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(max_length=50)),
                ('duration_minutes', models.IntegerField()),
                ('exercises', djongo.models.fields.JSONField(default=list)),
                ('target_muscles', djongo.models.fields.JSONField(default=list)),
                ('equipment_needed', djongo.models.fields.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workouts',
                'ordering': ['difficulty', 'name'],
            },
        ),
    ]
